steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/powerrank-1ff6b/powerscore-backend:1.0.0', '.']

  # Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/powerrank-1ff6b/powerscore-backend:1.0.0']

  # Deploy the app to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'my-app'
      - '--image'
      - 'gcr.io/powerrank-1ff6b/powerscore-backend:1.0.0'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
